[package]
name = "photomem"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
photomem-core.workspace = true
photomem-config.workspace = true
photomem-store.workspace = true
photomem-images.workspace = true
chrono.workspace = true
serde.workspace = true
arboard = { version = "3", default-features = false, features = ["wayland-data-control", "image-data"] }
base64 = "0.22"
anyhow.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
